### ISSUE TITLE
make withDelayBetweenTries() method in RetryConfigBuilder only accept a Duration object

### ISSUE THREAD

**Issue by elennick** [elennick/retry4j#17]

**Comment by dmcneil** [comment]
What do you think about something like this:
```
public RetryConfigBuilder withDelayBetweenTries(long duration, ChronoUnit unit) {
     config.setDelayBetweenRetries(Duration.of(amount, unit));
     return this;
}
```

And just getting rid of the `withDelayBetweenTries(int)`, `withDelayBetweenTries(long)` and `withDelayBetweenTries(Duration)`? This gives some nice readability, too, such as:
```
RetryConfig config = new RetryConfigBuilder()
     .withMaxNumberOfTries(5)
     .withDelayBetweenTries(5, SECONDS) // static import ChronoUnit
     .build();
```

**Comment by elennick** [comment]
@dmcneil i like that a lot actually, goes really well with the idea of the config builder being very fluent and readable... that being said I think i'd like to still let folks specify a Duration object if they wanted, so maybe get rid of the the methods that take an int/long and have two signatures that take

    .withDelayBetweenTries(int, ChronoUnit)

or

    .withDelayBetweenTries(Duration)

**Comment by elennick** [comment]
@dmcneil resolved this and its now merged
