### ISSUE TITLE
create a call executor builder or builders

### ISSUE THREAD

**Issue by elennick** [elennick/retry4j#28]
use the builder pattern to construct and utilize the **CallExecutor** and **AsyncCallExecutor**... something like:

`CallExecutorBuilder.newCall(<here the callable>).withConfig(<the configuration>).onRetryFailThen(<the action>).execute();`

**Comment by elennick** [comment]
to be resolved by PR #75

**Comment by raghavan20** [comment]
can this issue be closed given PR #75 is merged?

**Comment by elennick** [comment]
@raghavan20 i usually resolve issues when i do a release that includes their resolution... let me try to get something out in the next day or so and then ill close them

**Comment by elennick** [comment]
fixed in release 0.15.0
