### ISSUE TITLE
How to abort a running retry?

### ISSUE THREAD

**Issue by RedShift1** [elennick/retry4j#35]
How do you abort a running retry? For example cleanup when exiting?

**Comment by RedShift1** [comment]
@elennick

**Comment by elennick** [comment]
@RedShift1 there are a few ways you could conceivably do this:

(1) throw an exception that is not specified to retry on... that will result in execution ceasing and the executor throwing up an unchecked ```UnexpectedException``` (probably not the best approach)

(2) the logic in your Callable block could simply recognize a situation where it wants to abort and return without throwing any exceptions (what i would recommend)

**Comment by elennick** [comment]
@RedShift1 i realized after responding that i actually didnt address how you could abort execution and im not sure if that's something i would even want to include... ill have to think about it... regardless i did implement your other suggesttion of an OnCompletionListener and it is now in the latest release 0.7.0... feel free to check it out if you are interested
