### ISSUE TITLE
Exponential backoff algorithm not working correctly

### ISSUE THREAD

**Issue by fdlk** [elennick/retry4j#36]
I am running into these three issues in the current implementation:
1. If `numberOfTriesFailed` equals `1`, backoff value always equals `0`. I'd expect it to equal the `delayBetweenAttempts` parameter.
2. `backoffStrategy.getMillisToWait(5, Duration.ofMillis(100))` equals `1500`, I'd expect it to equal `1000 * 2^4` so `1600`.
3. If `numberOfTriesFailed` becomes large, backoff value becomes negative. I'd expect it to top off at max long value.

**Comment by elennick** [comment]
@fdlk hey Fleur, my apologies for the late reply, just noticed this... PR looks good and I merged it, thanks for the fix!

**Comment by elennick** [comment]
@fdlk 0.7.0 is now released which includes your changes

**Comment by fdlk** [comment]
@elennick Great! Thanks!
