### ISSUE TITLE
Retry on any exception except excluded ones

### ISSUE THREAD

**Issue by mkopylec** [elennick/retry4j#38]
Hi,
it will be nice to have a method like:
`retryOnAnyExceptionExcluding(Class<? extends Exception>... exceptions)`

**Comment by elennick** [comment]
@mkopylec i have added configuration and logic based on your suggestion, please feel free to upgrade to 0.7.0 and check it out when you're ready

**Comment by mkopylec** [comment]
Great, I'll try it soon. Thanks!

**Comment by mkopylec** [comment]
Couple of issues here.
```java
    public static void main(String[] args) {
        RetryConfig config = new RetryConfigBuilder()
                .withMaxNumberOfTries(3)
                .withNoWaitBackoff()
                .withDelayBetweenTries(0, ChronoUnit.MILLIS)
                .retryOnAnyExceptionExcluding(RuntimeException.class)
                .build();
        new CallExecutor<String>(config).execute(() -> {
            throw new Exception("error");
        });
    }
```
This code is throwing `UnexpectedException` but it should retry. `UnexpectedException` should be thrown if `RuntimeException` is thrown from callable.

Now this code:
```java
    public static void main(String[] args) {
        RetryConfig config = new RetryConfigBuilder()
                .withMaxNumberOfTries(3)
                .withNoWaitBackoff()
                .withDelayBetweenTries(0, ChronoUnit.MILLIS)
                .retryOnAnyExceptionExcluding(RuntimeException.class)
                .build();
        new CallExecutor<String>(config).execute(() -> {
            throw new IllegalStateException("error");
        });
    }
```
should not retry on `IllegalStateException` because it extends from `RuntimeException`.

**Comment by elennick** [comment]
I believe I have resolved this... check out release 0.7.1 when you get a chance and let me know if it looks better. I'll leave this issue open until then.

**Comment by mkopylec** [comment]
There is a similar issue with `retryOnSpecificExceptions()` method.
If you specify `retryOnSpecificExceptions(Exception.class)` it should be equivalent to `retryOnAnyException()` because all exceptions extends from `Exception` claas.

**Comment by elennick** [comment]
@mkopylec good catch... looks like I was using `isAssignableFrom()` incorrectly... i corrected this and added a bunch of very specific unit tests to verify that subclass/superclass/same class all behave as expected when using `retryOnSpecificExceptions`

check out 0.7.2 when you get a chance, i just pushed it to central

**Comment by mkopylec** [comment]
Thanks for fast issue solving :)
I'll check that out soon.
