### ISSUE TITLE
Allowing retry indefinitely

### ISSUE THREAD

**Issue by henryxwong** [elennick/retry4j#51]
For some use cases, you dont really want to fix numer of retry. It would be useful of allowing unspecified number of retry to retry indefinitely.

**Comment by elennick** [comment]
what would you think about another config option called something like `retryIndefinitely()` that you could use in place of `withMaxNumberOfTries()`?

**Comment by henryxwong** [comment]
sounds good, it make the api more explicit, especially for such specific use case

**Comment by elennick** [comment]
implemented with 0.10.0
