### ISSUE TITLE
clean up potential threading issues with listeners and call executors

### ISSUE THREAD

**Issue by elennick** [elennick/retry4j#61]
There are potential threading issues with the way the listener and call executor API's are currently set up. For example, it is possible to modify the listeners on an executor at any time even after construction, which could lead to modifications in retry behave while something is in the middle of executing. Another possibility could be that someone specifies behavior inside of a listener that is not thread safe and causes confusing, unpredictable or undesired behavior. This issue is to see what can be done to make these API's safer and to document best practices and potential side effects of mis-using these API's in multithreaded scenarios.

This relates to issue #28

**Comment by raghavan20** [comment]
I would like to share my thoughts on this issue.

I believe both `RetryConfig` and `RetryListener`s should be associated to `CallExecutor` in an immutable way.

- `RetryConfigBuilder` to hold temporary fields and builds an immutable `RetryConfig` on `build()`
  - adv: `RetryConfig` handed to `CallExecutor` will not be mutable later by client
  - disadv: backoff strategy `validateConfig` can only be called during `build()` once `RetryConfig` is built
- introduce `ImmutableRetryConfig` that would be created on `build()` of `RetryConfigBuilder`. for backoff strategy verification, `RetryConfig` can still be used. both RetryConfig and `ImmutableRetryConfig` can share same interface with getters.
  - adv: no change to existing behaviour on when validation would be attempted
  - disadv: additional class `ImmutableRetryConfig`


As suggested in issue #28, 

- `CallExecutor` can be created using `CallExecutorBuilder`
-  setters for listeners on `CallExecutor` can be removed

```
CallExecutor callExecutor = CallExecutorBuilder()
       .config(config)
       .failedTryListener(listener)
       .nextTryListener(listener)
       .failureListener(listener)
       .successListener(listener)
       .completionListener(listener)
       .build()
```

**Comment by elennick** [comment]
most of that sounds fine... i need to think about your retry config options... im not a big fan of the multiple config types, i think id rather just refactor the way config validation functions to work with the config being immutable
