### ISSUE TITLE
Bug in retrying on any exception exculding specific ones

### ISSUE THREAD

**Issue by mkopylec** [elennick/retry4j#68]
Hi.
I've discovered a bug in [the loop](https://github.com/elennick/retry4j/blob/master/src/main/java/com/evanlennick/retry4j/CallExecutor.java#L197)
If more than one exception is added to `RetryConfigBuilder.retryOnAnyExceptionExcluding(...)` then the functionality works only for the first exception in the `Set`. To work properly, all of the exceptions in the `Set` must be matched to exception thrown from `Callable<T>` try. 

I really need this fix ASAP :)

**Comment by elennick** [comment]
I can probably look at it this weekend and push out a fix if it's legit. If you want to create a PR and submit it sooner I can look at it as soon as you do.

**Comment by mkopylec** [comment]
This weekend is OK for me.
Thanks for a fast response.

**Comment by elennick** [comment]
@mkopylec should be fixed with 0.14.0 release, please check it out and let me know if you still have problems or not

**Comment by mkopylec** [comment]
It's fixed. Thanks!
