### ISSUE TITLE
Add support to set a delay from an exception

### ISSUE THREAD

**Issue by mstrdev** [elennick/retry4j#81]
Some API has supported special headers of status 29 Too Many Requests'. As an example - Intercom API

```
Rate Limit Headers
X-RateLimit-Limit: Maximum number of operations allowed in the current window
X-RateLimit-Remaining: Number of operations left in the current window.
X-RateLimit-Reset: Time when rate limit window will be reset as a Unix timestamp.
```

Which mapped to exception [RateLimitException](https://github.com/intercom/intercom-java/blob/fc9faa5d54c557d532305e24ee8e896af5566559/intercom-java/src/main/java/io/intercom/api/RateLimitException.java) with field `resetTime`
I want to set time where next try can call based by exception. 

Maybe add `exception` parameter to BackoffStrategy is a good solution

**Comment by elennick** [comment]
@mstrdev - I'm not sure I totally understand the suggestion... could you clarify a little bit with a more concrete example?
