### ISSUE TITLE
Thread safety of CallExecutor

### ISSUE THREAD

**Issue by steigma** [elennick/retry4j#85]
I'm wondering whether the CallExecutor is thread-safe? It seems to have a local member variable `status`, which is updated after/while making a retry. If several threads call the execute method concurrently, then the returned status may not be the correct one. Is this designed this way (in which case we may want to call it out that it is not thread-safe) or does it make sense to change it such that it is thread-safe, e.g., by avoiding this local member variable `status` (which seems easily possible by creating a new status object for each execution, passing it to the helper methods, and returning it)?

**Comment by elennick** [comment]
@steigma it is not thread-safe and there is another implementation of the executor that is intended to be used for this purpose: https://github.com/elennick/retry4j#async-support
